# Run with: mvn spring-boot:run -Dspring-boot.run.profiles=h2
spring.datasource.url=jdbc:h2:mem:jobportal;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

app.upload.dir=./uploads/resumes
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
