spring.application.name=job-portal-backend
server.port=8080

# ================= DATABASE =================
spring.datasource.url=jdbc:postgresql://dpg-d7ms7f3eo5us73evh3ag-a/jobportaldb_zijz
spring.datasource.username=jobportaldb_zijz_user
spring.datasource.password=qNkWMg1AcTulaJQB47xFetC8vmazMLIO
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ================= JWT =================
app.jwt.secret=ZmFrZUp3dFNlY3JldEtleUZvckpvYlBvcnRhbEFwcGxpY2F0aW9uMTIzNDU2Nzg5MA==
app.jwt.expiration-ms=86400000

# ================= CORS (IMPORTANT FIX) =================
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,https://dreambirdge-1.onrender.com

# ================= ADMIN =================
app.admin.email=admin@jobportal.com
app.admin.password=Admin@12345
app.admin.full-name=System Administrator

# ================= FILE UPLOAD =================
app.upload.dir=./uploads/resumes
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
